name: Run Prophet Model Training with MLflow Logging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_prophet_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
      run: pip install -r requirements.txt

      - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/ModelDevelopment/Training" >> $GITHUB_ENV

      - name: Set File permissions
        run: chmod +x ./ModelDevelopment/Training/train_model.py

      - name: Run Prophet Model Training Script
        run: |
          python Prophet.py

      - name: Notify on Success
        if: success()
        run: echo "✅ Model training and logging completed successfully!"

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Model training failed. Please check the logs for details."
