name: Debug GCP_PROJECT

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Debug GCP_PROJECT Value
      - name: Debug GCP_PROJECT Value
        run: echo "GCP_PROJECT is $GCP_PROJECT"
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

      # Step 4: Check if GCP_PROJECT is Configured
      - name: Check if GCP_PROJECT is Configured
        run: |
          if [ -z "$GCP_PROJECT" ]; then
            echo "GCP_PROJECT is not set!"
          else
            echo "GCP_PROJECT is configured!"
          fi
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

      # Step 5: Verify GCP_PROJECT by Running gcloud Command
      - name: Verify GCP_PROJECT
        run: |
          gcloud projects describe $GCP_PROJECT
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
