name: Model Save and Load Test

on:
  push:
    branches:
      - main

jobs:
  model-handler:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Authenticate with GCP
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Step 3: Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t model-handler-image:latest .

    # Step 4: Run the Docker Container
    - name: Run Model Save and Load Test
      run: |
        docker run --rm \
          -e GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json \
          -v ${{ secrets.GCP_CREDENTIALS }}:/app/service-account-key.json:ro \
          model-handler-image:latest
