name: Deploy to Vertex AI

on:
  push:
    branches:
      - vertexai  # Trigger the workflow on push to this branch

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Configure Docker Authentication for GCR
      - name: Configure Docker Authentication
        run: gcloud auth configure-docker

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg GCP_PROJECT=${{ secrets.GCP_PROJECT }} \
            --build-arg SECRET_NAME=service-account-key \
            -t gcr.io/${{ secrets.GCP_PROJECT }}/cloud-image:latest \
            -f ./cloud_run/Dockerfile ./cloud_run
      
      - name: Test Docker Image
        run: |
          docker run --rm \
            gcr.io/${{ secrets.GCP_PROJECT }}/cloud-image:latest

      # Step 5: Push Docker Image to GCR
      - name: Push Docker Image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/cloud-image:latest
