name: Run Docker on Push or Pull Request

# Trigger the workflow on push or pull request to the main branch (or specify other branches as needed)
on:
  push:
    branches:
      - model_local
  pull_request:
    branches:
      - model_local

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional, but useful for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my_model_pipeline -f ModelDevelopment/Dockerfile ModelDevelopment

      # Step 4: Run the Docker container
      - name: Run Docker container
        run: |
          docker run my_model_pipeline
