name: Run Prophet Model Training with MLflow Logging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_prophet_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Configure MLflow Environment Variables
        run: |
          echo "MLFLOW_TRACKING_URI=file://${{ github.workspace }}/mlruns" >> $GITHUB_ENV
          echo "MLFLOW_ARTIFACT_URI=${{ github.workspace }}/mlruns" >> $GITHUB_ENV

      - name: Create and Set Permissions for mlruns Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/mlruns
          chmod -R 777 $GITHUB_WORKSPACE/mlruns

      - name: Debug Environment Variables
        run: |
          echo "MLFLOW_TRACKING_URI is set to $MLFLOW_TRACKING_URI"
          echo "MLFLOW_ARTIFACT_URI is set to $MLFLOW_ARTIFACT_URI"

      - name: Run Prophet Model Training Script
        run: |
          chmod -R 777 $GITHUB_WORKSPACE  # Ensure full permissions for workspace files
          python ModelDevelopment/Training/Prophet.py

      - name: Upload MLflow Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: $GITHUB_WORKSPACE/mlruns

      - name: Notify on Success
        if: success()
        run: echo "✅ Model training and logging completed successfully!"

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Model training failed. Please check the logs for details."
