name: Testing with Pytest (train data)

on:
  push:
    branches:
      - main
    #  - test  # Run the tests on both the main and test branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # might change

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests in DataPreprocessing/test/train_data
      run: pytest DataPreprocessing/test/train_data/ --junitxml=pytest-report.xml
      continue-on-error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: pytest-report.xml

    - name: Notify on success
      if: success()
      run: echo "Tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Tests failed"
