name: Test Secret Access

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret (Masked)
        run: echo "Secret value is ${{ secrets.GCP_SA_KEY }}"
