name: Deploy to Vertex AI

on:
  push:
    branches:
      - vertexai  # Trigger the workflow on push to this branch

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Configure Docker Authentication for GCR
      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/vertex-training-image:latest -f ./vertex_testing/Dockerfile ./vertex_testing

      # Step 5: Push Docker Image to GCR
      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/vertex-training-image:latest

      # Step 6: Upload the Model to Vertex AI and Extract Model ID
      - name: Upload Model to Vertex AI
        id: upload_model
        run: |
          MODEL_ID=$(gcloud ai models upload \
            --region=us-central1 \
            --display-name=pm25-model \
            --container-image-uri=gcr.io/${{ secrets.GCP_PROJECT }}/vertex-training-image:latest \
            --format="value(name)")
          echo "MODEL_ID=$MODEL_ID" >> $GITHUB_ENV
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

      # Step 7: Create or Reuse an Endpoint
      - name: Create or Reuse Endpoint
        id: create_endpoint
        run: |
          ENDPOINT_NAME=$(gcloud ai endpoints list --region=us-central1 --filter="display_name=pm25-endpoint" --format="value(name)")
          if [ -z "$ENDPOINT_NAME" ]; then
            ENDPOINT_NAME=$(gcloud ai endpoints create --region=us-central1 --display-name=pm25-endpoint --format="value(name)")
          fi
          echo "ENDPOINT_NAME=$ENDPOINT_NAME" >> $GITHUB_ENV

      # Step 8: Deploy Model to Endpoint
      - name: Deploy Model to Endpoint
        run: |
          gcloud ai endpoints deploy-model $ENDPOINT_NAME \
            --region=us-central1 \
            --model=$MODEL_ID \
            --display-name=pm25-model-deployment \
            --machine-type=n1-standard-4 \
            --traffic-split=0=100
        env:
          MODEL_ID: ${{ env.MODEL_ID }}
          ENDPOINT_NAME: ${{ env.ENDPOINT_NAME }}
